version: '3'
services:
    db:
        image: 'postgres:13'
        restart: unless-stopped
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./db-data:/var/lib/postgresql/data/

    worker:
        image: 'ptrxyz/chemotion:1.0.3D0.1'
        restart: unless-stopped
        command: ["starteln"]
        environment:
            - CONFIG_ROLE="worker"
        depends_on:
            - 'db'
        volumes:
            - ./shared:/shared

    eln:
        image: 'ptrxyz/chemotion:1.0.3D0.1'
        restart: unless-stopped
        command: ["starteln"]
        depends_on:
            - 'db'
        expose:
            - '4000'
        ports:
            - 4000:4000
        volumes:
            - ./shared:/shared
