version: '3'
services:
    db:
        image: 'postgres:13'
        restart: unless-stopped
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ./db-data:/var/lib/postgresql/data/

    worker:
        image: 'ptrxyz/chemotion:21.06-3'
        command: ["start-worker"]
        depends_on:
            - 'db'
        volumes:
            - ./config:/config:ro
            - ./shared:/shared

    eln:
        image: 'ptrxyz/chemotion:21.06-3'
        command: ["start-eln"]
        depends_on:
            - 'db'
        expose:
            - '4000'
        ports:
            - 4000:4000
        volumes:
            - ./config:/config:ro
            - ./shared:/shared
