version: '3'
services:
    db:
        image: 'postgres:13'
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_USER=root

    eln:
        build: .
        depends_on:
            - db
        init: true
        expose:
            - '4000'
            - '4001'
