production:
  :url: <%= ENV['CONVERTER_URL'] || 'https://153.converter.hydrogen.scc.kit.edu/' %>
  :profile: <%= ENV['CONVERTER_PROFILE'] || 'dev-0000' %>
  :secret_key: <%= ENV['CONVERTER_SECRET'] || 'dev-0000' %>
  :timeout: 300
  :ext:
    - '.xy'
    - '.xls'
    - '.xlsx'
    - '.txt'
    - '.brml'
    - '.dta'
    - '.pssession'
