production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] || 'dev-0000' %>
  pool: 5
  username: <%= ENV['DB_USER'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'postgres' %>
  host: <%= ENV['DB_HOST'] || "db" %>
  port: <%= ENV['DB_PORT'] || '5432' %>
