# production:
#   :url: '141.spectra.hydrogen.scc.kit.edu'
#   :port: '443'
#   :nmriumwrapper:
#     :protocol: 'https'
#     :url: 'nmriumdev.nmrxiv.org'
#     :port: ''

production:
  :chemspectra:
    :url: <%= ENV['SPECTRA_URL'] || 'https://153.spectra.hydrogen.scc.kit.edu' %>
  :nmriumwrapper:
    # :url: 'http://nmrium-0-2-1-bare.eln.hydrogen.scc.kit.edu:4080'
    :url: <%= ENV['NMRIUM_URL'] || 'https://nmrium-0-2-1-secure.eln.hydrogen.scc.kit.edu' %>
