production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  # Ensure the secret key token is also set as as env variable in the
  # OnlyOffice (ver. 7+) container: -e JWT_SECRET=my_jwt_secret
  only_office_secret_key_base: <%= ENV["ONLY_OFFICE_SECRET_KEY_BASE"] %>
  test:
  test2: "null"
