version: "3"
services:
  db:
    image: postgres:13
    restart: unless-stopped
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /tmp/db-data:/var/lib/postgresql/data/

  msconvert:
    image: chemotion-build:msconvert
    restart: unless-stopped
    hostname: msconvert
    volumes:
      - spectra:/shared:rw
  
  spectra:
    image: chemotion-build:spectra
    restart: unless-stopped
    hostname: spectra
    volumes:
      - spectra:/shared:rw
    depends_on:
      - msconvert

  worker:
    image: chemotion-build:eln
    restart: unless-stopped
    environment:
      - CONFIG_ROLE=worker
    depends_on:
      - db
      - eln
      - spectra
    volumes:
      - ../eln/embed:/embed
      - chemotion_data:/chemotion/data/
      - chemotion:/chemotion/app

  eln:
    image: chemotion-build:eln
    restart: unless-stopped
    environment:
      - CONFIG_ROLE=eln
      - SMTP_ADDRESS="smtp.google.de"
    depends_on:
      - db
      - spectra
    volumes:
      - ../eln/embed:/embed
      - ./shared/pullin:/shared
      - ./shared/backup:/backup
      - chemotion_data:/chemotion/data/
      - chemotion:/chemotion/app
    ports:
      - 4001:4000

volumes:
  chemotion:
  chemotion_data:
  spectra: